ALTER TABLE users ADD COLUMN IF NOT EXISTS favorite_console TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS favorite_windows TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS nostalgic_memory TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS favorite_messenger TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS things_love TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS things_dislike TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS biggest_dream TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS admire_people TEXT;
